# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'AccessCheckout' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AccessCheckout

  target 'AccessCheckoutTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Mockingjay'
    pod 'PactConsumerSwift'
  end

  target 'AccessCheckoutDemo' do
    inherit! :search_paths
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    #use_frameworks!
    pod 'Mockingjay/Core'

  end

  target 'AccessCheckoutDemoUITests' do
    inherit! :search_paths
    # Pods for testing

  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.2'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
