# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'AccessCheckoutDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'AccessCheckoutSDK', :path => '../'
  pod 'Swifter', '1.5.0'

  target 'AccessCheckoutDemoUITests' do
    # inherit! :search_paths
    # Pods for testing
  end

end
