# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

# ignore all warnings from all pods
inhibit_all_warnings!

target 'AccessCheckoutSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  target 'AccessCheckoutSDKTests' do
    inherit! :search_paths
    pod 'Swifter', '1.5.0'
    pod 'Cuckoo', '1.9.1'
  end
  
  target 'AccessCheckoutSDKPactTests' do
    inherit! :search_paths
    pod 'PactConsumerSwift', '0.10.2'
    pod 'Swifter', '1.5.0'
  end

end
