platform :ios, '8.0'

# ignore all warnings from all pods
inhibit_all_warnings!
use_frameworks!



target 'AccessCheckoutSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for AccessCheckoutSDK

  target 'AccessCheckoutSDKPactTests' do
    platform :ios, '9.0'
    inherit! :search_paths
    # Pods for testing
    pod 'PactConsumerSwift'
  end

  target 'AccessCheckoutSDKTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Mockingjay', '~> 3.0.0-alpha.1'
  end

end

target 'AccessCheckoutDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  
  # Pods for AccessCheckoutDemo
  pod 'Mockingjay/Core', '~> 3.0.0-alpha.1'
  
  target 'AccessCheckoutDemoUITests' do
    inherit! :search_paths
    # inherit! :complete
    # Pods for testing
  end
  
end
