# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'AccessCheckoutSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AccessCheckoutSDK

  target 'AccessCheckoutSDKTests' do
    inherit! :search_paths
    pod 'Mockingjay', '~> 3.0.0-alpha.1'
  end
  
  target 'AccessCheckoutSDKPactTests' do
    inherit! :search_paths
    pod 'PactConsumerSwift'
  end

end
